[tool.pylint.main]
exit-zero = true
ignore = ["node_modules"]
jobs = 0
[tool.pylint.basic]
# We use uppercase acronyms like HTML, IMAP, etc.
module-rgx = "^[_a-zA-Z0-9+]+$"
function-rgx = "^[_a-zA-Z0-9+]+$"
[tool.pylint."messages control"]
# Code like R0912 is better to order disables by category.
disable = [
  "C1804",  # use-implicit-booleaness-not-comparison-to-string
  "I0011",  # locally-disabled
  "I0020",  # suppressed-message
  "R0912",  # too-many-branches
  "R0913",  # too-many-arguments
  "R0914",  # too-many-locals
  "R0915",  # too-many-statements
  "R0917",  # too-many-positional-arguments
]
enable = "all"
[tool.pylint.reports]
output-format = "colorized"
