[lint]
select = ["ALL", "D211"]
# ignore = ["D203", "D212", "D404"]
ignore = [
  "C901",
  "D203",
  "D205",
  "D212",
  "D404",
  "EM101",
  "ERA001",
  "N802",
  "PLR0912",
  "PLR0913",
  "PLR0915",
  "T201",
  "TRY003",
  "UP045",
]
[lint.per-file-ignores]
"build_and_checks_dependencies/licenses_templates/*.py" = ["INP001"]
